'use client';

export interface AssetInfo {
  name: string;
  path: string;
  category: 'kingdom' | 'env' | 'tree';
}

export interface MaterialInfo {
  id: string;
  name: string;
  diffuse?: string;
  normal?: string;
  roughness?: string;
  displacement?: string;
}

export const FULL_ASSET_LIBRARY: AssetInfo[] = [
  // KINGDOM Assets
  { name: "Bridge Draw", path: "/kingdom/bridge-draw.glb", category: 'kingdom' },
  { name: "Bridge Straight Pillar", path: "/kingdom/bridge-straight-pillar.glb", category: 'kingdom' },
  { name: "Bridge Straight", path: "/kingdom/bridge-straight.glb", category: 'kingdom' },
  { name: "Door", path: "/kingdom/door.glb", category: 'kingdom' },
  { name: "Flag Banner Long", path: "/kingdom/flag-banner-long.glb", category: 'kingdom' },
  { name: "Flag Banner Short", path: "/kingdom/flag-banner-short.glb", category: 'kingdom' },
  { name: "Flag Pennant", path: "/kingdom/flag-pennant.glb", category: 'kingdom' },
  { name: "Flag Wide", path: "/kingdom/flag-wide.glb", category: 'kingdom' },
  { name: "Flag", path: "/kingdom/flag.glb", category: 'kingdom' },
  { name: "Gate", path: "/kingdom/gate.glb", category: 'kingdom' },
  { name: "Ground Hills", path: "/kingdom/ground-hills.glb", category: 'kingdom' },
  { name: "Ground", path: "/kingdom/ground.glb", category: 'kingdom' },
  { name: "Metal Gate", path: "/kingdom/metal-gate.glb", category: 'kingdom' },
  { name: "Rocks Large", path: "/kingdom/rocks-large.glb", category: 'kingdom' },
  { name: "Rocks Small", path: "/kingdom/rocks-small.glb", category: 'kingdom' },
  { name: "Siege Ballista Demolished", path: "/kingdom/siege-ballista-demolished.glb", category: 'kingdom' },
  { name: "Siege Ballista", path: "/kingdom/siege-ballista.glb", category: 'kingdom' },
  { name: "Siege Catapult Demolished", path: "/kingdom/siege-catapult-demolished.glb", category: 'kingdom' },
  { name: "Siege Catapult", path: "/kingdom/siege-catapult.glb", category: 'kingdom' },
  { name: "Siege Ram Demolished", path: "/kingdom/siege-ram-demolished.glb", category: 'kingdom' },
  { name: "Siege Ram", path: "/kingdom/siege-ram.glb", category: 'kingdom' },
  { name: "Siege Tower Demolished", path: "/kingdom/siege-tower-demolished.glb", category: 'kingdom' },
  { name: "Siege Tower", path: "/kingdom/siege-tower.glb", category: 'kingdom' },
  { name: "Siege Trebuchet Demolished", path: "/kingdom/siege-trebuchet-demolished.glb", category: 'kingdom' },
  { name: "Siege Trebuchet", path: "/kingdom/siege-trebuchet.glb", category: 'kingdom' },
  { name: "Stairs Stone Square", path: "/kingdom/stairs-stone-square.glb", category: 'kingdom' },
  { name: "Stairs Stone", path: "/kingdom/stairs-stone.glb", category: 'kingdom' },
  { name: "Tower Base", path: "/kingdom/tower-base.glb", category: 'kingdom' },
  { name: "Tower Hexagon Base", path: "/kingdom/tower-hexagon-base.glb", category: 'kingdom' },
  { name: "Tower Hexagon Mid", path: "/kingdom/tower-hexagon-mid.glb", category: 'kingdom' },
  { name: "Tower Hexagon Roof Secondary", path: "/kingdom/tower-hexagon-roof-secondary.glb", category: 'kingdom' },
  { name: "Tower Hexagon Roof", path: "/kingdom/tower-hexagon-roof.glb", category: 'kingdom' },
  { name: "Tower Hexagon Top Wood", path: "/kingdom/tower-hexagon-top-wood.glb", category: 'kingdom' },
  { name: "Tower Hexagon Top", path: "/kingdom/tower-hexagon-top.glb", category: 'kingdom' },
  { name: "Tower Slant Roof", path: "/kingdom/tower-slant-roof.glb", category: 'kingdom' },
  { name: "Tower Square Arch", path: "/kingdom/tower-square-arch.glb", category: 'kingdom' },
  { name: "Tower Square Base Border", path: "/kingdom/tower-square-base-border.glb", category: 'kingdom' },
  { name: "Tower Square Base Color", path: "/kingdom/tower-square-base-color.glb", category: 'kingdom' },
  { name: "Tower Square Base", path: "/kingdom/tower-square-base.glb", category: 'kingdom' },
  { name: "Tower Square Mid Color", path: "/kingdom/tower-square-mid-color.glb", category: 'kingdom' },
  { name: "Tower Square Mid Door", path: "/kingdom/tower-square-mid-door.glb", category: 'kingdom' },
  { name: "Tower Square Mid Open Simple", path: "/kingdom/tower-square-mid-open-simple.glb", category: 'kingdom' },
  { name: "Tower Square Mid Open", path: "/kingdom/tower-square-mid-open.glb", category: 'kingdom' },
  { name: "Tower Square Mid Windows", path: "/kingdom/tower-square-mid-windows.glb", category: 'kingdom' },
  { name: "Tower Square Mid", path: "/kingdom/tower-square-mid.glb", category: 'kingdom' },
  { name: "Tower Square Roof", path: "/kingdom/tower-square-roof.glb", category: 'kingdom' },
  { name: "Tower Square Top Color", path: "/kingdom/tower-square-top-color.glb", category: 'kingdom' },
  { name: "Tower Square Top Roof High Windows", path: "/kingdom/tower-square-top-roof-high-windows.glb", category: 'kingdom' },
  { name: "Tower Square Top Roof High", path: "/kingdom/tower-square-top-roof-high.glb", category: 'kingdom' },
  { name: "Tower Square Top Roof Rounded", path: "/kingdom/tower-square-top-roof-rounded.glb", category: 'kingdom' },
  { name: "Tower Square Top Roof", path: "/kingdom/tower-square-top-roof.glb", category: 'kingdom' },
  { name: "Tower Square Top", path: "/kingdom/tower-square-top.glb", category: 'kingdom' },
  { name: "Tower Square", path: "/kingdom/tower-square.glb", category: 'kingdom' },
  { name: "Tower Top", path: "/kingdom/tower-top.glb", category: 'kingdom' },
  { name: "Tree Large", path: "/kingdom/tree-large.glb", category: 'kingdom' },
  { name: "Tree Log", path: "/kingdom/tree-log.glb", category: 'kingdom' },
  { name: "Tree Small", path: "/kingdom/tree-small.glb", category: 'kingdom' },
  { name: "Tree Trunk", path: "/kingdom/tree-trunk.glb", category: 'kingdom' },
  { name: "Wall Corner Half Tower", path: "/kingdom/wall-corner-half-tower.glb", category: 'kingdom' },
  { name: "Wall Corner Half", path: "/kingdom/wall-corner-half.glb", category: 'kingdom' },
  { name: "Wall Corner Slant", path: "/kingdom/wall-corner-slant.glb", category: 'kingdom' },
  { name: "Wall Corner", path: "/kingdom/wall-corner.glb", category: 'kingdom' },
  { name: "Wall Doorway", path: "/kingdom/wall-doorway.glb", category: 'kingdom' },
  { name: "Wall Half Modular", path: "/kingdom/wall-half-modular.glb", category: 'kingdom' },
  { name: "Wall Half", path: "/kingdom/wall-half.glb", category: 'kingdom' },
  { name: "Wall Narrow Corner", path: "/kingdom/wall-narrow-corner.glb", category: 'kingdom' },
  { name: "Wall Narrow Gate", path: "/kingdom/wall-narrow-gate.glb", category: 'kingdom' },
  { name: "Wall Narrow Stairs Rail", path: "/kingdom/wall-narrow-stairs-rail.glb", category: 'kingdom' },
  { name: "Wall Narrow Stairs", path: "/kingdom/wall-narrow-stairs.glb", category: 'kingdom' },
  { name: "Wall Narrow Wood Fence", path: "/kingdom/wall-narrow-wood-fence.glb", category: 'kingdom' },
  { name: "Wall Narrow Wood", path: "/kingdom/wall-narrow-wood.glb", category: 'kingdom' },
  { name: "Wall Narrow", path: "/kingdom/wall-narrow.glb", category: 'kingdom' },
  { name: "Wall Pillar", path: "/kingdom/wall-pillar.glb", category: 'kingdom' },
  { name: "Wall Stud", path: "/kingdom/wall-stud.glb", category: 'kingdom' },
  { name: "Wall To Narrow", path: "/kingdom/wall-to-narrow.glb", category: 'kingdom' },
  { name: "Wall", path: "/kingdom/wall.glb", category: 'kingdom' },

  // ENV Assets
  { name: "Arrow", path: "/assets-env/arrow.glb", category: 'env' },
  { name: "Arrows", path: "/assets-env/arrows.glb", category: 'env' },
  { name: "Barrel", path: "/assets-env/barrel.glb", category: 'env' },
  { name: "Block Grass Corner Low", path: "/assets-env/block-grass-corner-low.glb", category: 'env' },
  { name: "Block Grass Corner Overhang Low", path: "/assets-env/block-grass-corner-overhang-low.glb", category: 'env' },
  { name: "Block Grass Corner Overhang", path: "/assets-env/block-grass-corner-overhang.glb", category: 'env' },
  { name: "Block Grass Corner", path: "/assets-env/block-grass-corner.glb", category: 'env' },
  { name: "Block Grass Curve Half", path: "/assets-env/block-grass-curve-half.glb", category: 'env' },
  { name: "Block Grass Curve Low", path: "/assets-env/block-grass-curve-low.glb", category: 'env' },
  { name: "Block Grass Curve", path: "/assets-env/block-grass-curve.glb", category: 'env' },
  { name: "Block Grass Edge", path: "/assets-env/block-grass-edge.glb", category: 'env' },
  { name: "Block Grass Hexagon", path: "/assets-env/block-grass-hexagon.glb", category: 'env' },
  { name: "Block Grass Large Slope Narrow", path: "/assets-env/block-grass-large-slope-narrow.glb", category: 'env' },
  { name: "Block Grass Large Slope Steep Narrow", path: "/assets-env/block-grass-large-slope-steep-narrow.glb", category: 'env' },
  { name: "Block Grass Large Slope Steep", path: "/assets-env/block-grass-large-slope-steep.glb", category: 'env' },
  { name: "Block Grass Large Slope", path: "/assets-env/block-grass-large-slope.glb", category: 'env' },
  { name: "Block Grass Large Tall", path: "/assets-env/block-grass-large-tall.glb", category: 'env' },
  { name: "Block Grass Large", path: "/assets-env/block-grass-large.glb", category: 'env' },
  { name: "Block Grass Long", path: "/assets-env/block-grass-long.glb", category: 'env' },
  { name: "Block Grass Low Hexagon", path: "/assets-env/block-grass-low-hexagon.glb", category: 'env' },
  { name: "Block Grass Low Large", path: "/assets-env/block-grass-low-large.glb", category: 'env' },
  { name: "Block Grass Low Long", path: "/assets-env/block-grass-low-long.glb", category: 'env' },
  { name: "Block Grass Low Narrow", path: "/assets-env/block-grass-low-narrow.glb", category: 'env' },
  { name: "Block Grass Low", path: "/assets-env/block-grass-low.glb", category: 'env' },
  { name: "Block Grass Narrow", path: "/assets-env/block-grass-narrow.glb", category: 'env' },
  { name: "Block Grass Overhang Corner", path: "/assets-env/block-grass-overhang-corner.glb", category: 'env' },
  { name: "Block Grass Overhang Edge", path: "/assets-env/block-grass-overhang-edge.glb", category: 'env' },
  { name: "Block Grass Overhang Hexagon", path: "/assets-env/block-grass-overhang-hexagon.glb", category: 'env' },
  { name: "Block Grass Overhang Large Slope Narrow", path: "/assets-env/block-grass-overhang-large-slope-narrow.glb", category: 'env' },
  { name: "Block Grass Overhang Large Slope Steep Narrow", path: "/assets-env/block-grass-overhang-large-slope-steep-narrow.glb", category: 'env' },
  { name: "Block Grass Overhang Large Slope Steep", path: "/assets-env/block-grass-overhang-large-slope-steep.glb", category: 'env' },
  { name: "Block Grass Overhang Large Slope", path: "/assets-env/block-grass-overhang-large-slope.glb", category: 'env' },
  { name: "Block Grass Overhang Large Tall", path: "/assets-env/block-grass-overhang-large-tall.glb", category: 'env' },
  { name: "Block Grass Overhang Large", path: "/assets-env/block-grass-overhang-large.glb", category: 'env' },
  { name: "Block Grass Overhang Long", path: "/assets-env/block-grass-overhang-long.glb", category: 'env' },
  { name: "Block Grass Overhang Low Hexagon", path: "/assets-env/block-grass-overhang-low-hexagon.glb", category: 'env' },
  { name: "Block Grass Overhang Low Large", path: "/assets-env/block-grass-overhang-low-large.glb", category: 'env' },
  { name: "Block Grass Overhang Low Long", path: "/assets-env/block-grass-overhang-low-long.glb", category: 'env' },
  { name: "Block Grass Overhang Low Narrow", path: "/assets-env/block-grass-overhang-low-narrow.glb", category: 'env' },
  { name: "Block Grass Overhang Low", path: "/assets-env/block-grass-overhang-low.glb", category: 'env' },
  { name: "Block Grass Overhang Narrow", path: "/assets-env/block-grass-overhang-narrow.glb", category: 'env' },
  { name: "Block Grass", path: "/assets-env/block-grass.glb", category: 'env' },
  { name: "Block Moving Blue", path: "/assets-env/block-moving-blue.glb", category: 'env' },
  { name: "Block Moving Large", path: "/assets-env/block-moving-large.glb", category: 'env' },
  { name: "Block Moving", path: "/assets-env/block-moving.glb", category: 'env' },
  { name: "Block Snow Corner Low", path: "/assets-env/block-snow-corner-low.glb", category: 'env' },
  { name: "Block Snow Corner Overhang Low", path: "/assets-env/block-snow-corner-overhang-low.glb", category: 'env' },
  { name: "Block Snow Corner Overhang", path: "/assets-env/block-snow-corner-overhang.glb", category: 'env' },
  { name: "Block Snow Corner", path: "/assets-env/block-snow-corner.glb", category: 'env' },
  { name: "Block Snow Curve Half", path: "/assets-env/block-snow-curve-half.glb", category: 'env' },
  { name: "Block Snow Curve Low", path: "/assets-env/block-snow-curve-low.glb", category: 'env' },
  { name: "Block Snow Curve", path: "/assets-env/block-snow-curve.glb", category: 'env' },
  { name: "Block Snow Edge", path: "/assets-env/block-snow-edge.glb", category: 'env' },
  { name: "Block Snow Hexagon", path: "/assets-env/block-snow-hexagon.glb", category: 'env' },
  { name: "Block Snow Large Slope Narrow", path: "/assets-env/block-snow-large-slope-narrow.glb", category: 'env' },
  { name: "Block Snow Large Slope Steep Narrow", path: "/assets-env/block-snow-large-slope-steep-narrow.glb", category: 'env' },
  { name: "Block Snow Large Slope Steep", path: "/assets-env/block-snow-large-slope-steep.glb", category: 'env' },
  { name: "Block Snow Large Slope", path: "/assets-env/block-snow-large-slope.glb", category: 'env' },
  { name: "Block Snow Large Tall", path: "/assets-env/block-snow-large-tall.glb", category: 'env' },
  { name: "Block Snow Large", path: "/assets-env/block-snow-large.glb", category: 'env' },
  { name: "Block Snow Long", path: "/assets-env/block-snow-long.glb", category: 'env' },
  { name: "Block Snow Low Hexagon", path: "/assets-env/block-snow-low-hexagon.glb", category: 'env' },
  { name: "Block Snow Low Large", path: "/assets-env/block-snow-low-large.glb", category: 'env' },
  { name: "Block Snow Low Long", path: "/assets-env/block-snow-low-long.glb", category: 'env' },
  { name: "Block Snow Low Narrow", path: "/assets-env/block-snow-low-narrow.glb", category: 'env' },
  { name: "Block Snow Low", path: "/assets-env/block-snow-low.glb", category: 'env' },
  { name: "Block Snow Narrow", path: "/assets-env/block-snow-narrow.glb", category: 'env' },
  { name: "Block Snow Overhang Corner", path: "/assets-env/block-snow-overhang-corner.glb", category: 'env' },
  { name: "Block Snow Overhang Edge", path: "/assets-env/block-snow-overhang-edge.glb", category: 'env' },
  { name: "Block Snow Overhang Hexagon", path: "/assets-env/block-snow-overhang-hexagon.glb", category: 'env' },
  { name: "Block Snow Overhang Large Slope Narrow", path: "/assets-env/block-snow-overhang-large-slope-narrow.glb", category: 'env' },
  { name: "Block Snow Overhang Large Slope Steep Narrow", path: "/assets-env/block-snow-overhang-large-slope-steep-narrow.glb", category: 'env' },
  { name: "Block Snow Overhang Large Slope Steep", path: "/assets-env/block-snow-overhang-large-slope-steep.glb", category: 'env' },
  { name: "Block Snow Overhang Large Slope", path: "/assets-env/block-snow-overhang-large-slope.glb", category: 'env' },
  { name: "Block Snow Overhang Large Tall", path: "/assets-env/block-snow-overhang-large-tall.glb", category: 'env' },
  { name: "Block Snow Overhang Large", path: "/assets-env/block-snow-overhang-large.glb", category: 'env' },
  { name: "Block Snow Overhang Long", path: "/assets-env/block-snow-overhang-long.glb", category: 'env' },
  { name: "Block Snow Overhang Low Hexagon", path: "/assets-env/block-snow-overhang-low-hexagon.glb", category: 'env' },
  { name: "Block Snow Overhang Low Large", path: "/assets-env/block-snow-overhang-low-large.glb", category: 'env' },
  { name: "Block Snow Overhang Low Long", path: "/assets-env/block-snow-overhang-low-long.glb", category: 'env' },
  { name: "Block Snow Overhang Low Narrow", path: "/assets-env/block-snow-overhang-low-narrow.glb", category: 'env' },
  { name: "Block Snow Overhang Low", path: "/assets-env/block-snow-overhang-low.glb", category: 'env' },
  { name: "Block Snow Overhang Narrow", path: "/assets-env/block-snow-overhang-narrow.glb", category: 'env' },
  { name: "Block Snow", path: "/assets-env/block-snow.glb", category: 'env' },
  { name: "Bomb", path: "/assets-env/bomb.glb", category: 'env' },
  { name: "Brick", path: "/assets-env/brick.glb", category: 'env' },
  { name: "Button Round", path: "/assets-env/button-round.glb", category: 'env' },
  { name: "Button Square", path: "/assets-env/button-square.glb", category: 'env' },
  { name: "Character Oobi", path: "/assets-env/character-oobi.glb", category: 'env' },
  { name: "Character Oodi", path: "/assets-env/character-oodi.glb", category: 'env' },
  { name: "Character Ooli", path: "/assets-env/character-ooli.glb", category: 'env' },
  { name: "Character Oopi", path: "/assets-env/character-oopi.glb", category: 'env' },
  { name: "Character Oozi", path: "/assets-env/character-oozi.glb", category: 'env' },
  { name: "Chest", path: "/assets-env/chest.glb", category: 'env' },
  { name: "Coin Bronze", path: "/assets-env/coin-bronze.glb", category: 'env' },
  { name: "Coin Gold", path: "/assets-env/coin-gold.glb", category: 'env' },
  { name: "Coin Silver", path: "/assets-env/coin-silver.glb", category: 'env' },
  { name: "Conveyor Belt", path: "/assets-env/conveyor-belt.glb", category: 'env' },
  { name: "Crate Item Strong", path: "/assets-env/crate-item-strong.glb", category: 'env' },
  { name: "Crate Item", path: "/assets-env/crate-item.glb", category: 'env' },
  { name: "Crate Strong", path: "/assets-env/crate-strong.glb", category: 'env' },
  { name: "Crate", path: "/assets-env/crate.glb", category: 'env' },
  { name: "Door Large Open", path: "/assets-env/door-large-open.glb", category: 'env' },
  { name: "Door Open", path: "/assets-env/door-open.glb", category: 'env' },
  { name: "Door Rotate Large", path: "/assets-env/door-rotate-large.glb", category: 'env' },
  { name: "Door Rotate", path: "/assets-env/door-rotate.glb", category: 'env' },
  { name: "Fence Broken", path: "/assets-env/fence-broken.glb", category: 'env' },
  { name: "Fence Corner Curved", path: "/assets-env/fence-corner-curved.glb", category: 'env' },
  { name: "Fence Corner", path: "/assets-env/fence-corner.glb", category: 'env' },
  { name: "Fence Low Broken", path: "/assets-env/fence-low-broken.glb", category: 'env' },
  { name: "Fence Low Corner Curved", path: "/assets-env/fence-low-corner-curved.glb", category: 'env' },
  { name: "Fence Low Corner", path: "/assets-env/fence-low-corner.glb", category: 'env' },
  { name: "Fence Low Straight", path: "/assets-env/fence-low-straight.glb", category: 'env' },
  { name: "Fence Rope", path: "/assets-env/fence-rope.glb", category: 'env' },
  { name: "Fence Straight", path: "/assets-env/fence-straight.glb", category: 'env' },
  { name: "Flag", path: "/assets-env/flag.glb", category: 'env' },
  { name: "Flowers Tall", path: "/assets-env/flowers-tall.glb", category: 'env' },
  { name: "Flowers", path: "/assets-env/flowers.glb", category: 'env' },
  { name: "Grass", path: "/assets-env/grass.glb", category: 'env' },
  { name: "Heart", path: "/assets-env/heart.glb", category: 'env' },
  { name: "Hedge Corner", path: "/assets-env/hedge-corner.glb", category: 'env' },
  { name: "Hedge", path: "/assets-env/hedge.glb", category: 'env' },
  { name: "Jewel", path: "/assets-env/jewel.glb", category: 'env' },
  { name: "Key", path: "/assets-env/key.glb", category: 'env' },
  { name: "Ladder Broken", path: "/assets-env/ladder-broken.glb", category: 'env' },
  { name: "Ladder Long", path: "/assets-env/ladder-long.glb", category: 'env' },
  { name: "Ladder", path: "/assets-env/ladder.glb", category: 'env' },
  { name: "Lever", path: "/assets-env/lever.glb", category: 'env' },
  { name: "Lock", path: "/assets-env/lock.glb", category: 'env' },
  { name: "Mushrooms", path: "/assets-env/mushrooms.glb", category: 'env' },
  { name: "Pipe", path: "/assets-env/pipe.glb", category: 'env' },
  { name: "Plant", path: "/assets-env/plant.glb", category: 'env' },
  { name: "Platform Fortified", path: "/assets-env/platform-fortified.glb", category: 'env' },
  { name: "Platform Overhang", path: "/assets-env/platform-overhang.glb", category: 'env' },
  { name: "Platform Ramp", path: "/assets-env/platform-ramp.glb", category: 'env' },
  { name: "Platform", path: "/assets-env/platform.glb", category: 'env' },
  { name: "Poles", path: "/assets-env/poles.glb", category: 'env' },
  { name: "Rocks", path: "/assets-env/rocks.glb", category: 'env' },
  { name: "Saw", path: "/assets-env/saw.glb", category: 'env' },
  { name: "Sign", path: "/assets-env/sign.glb", category: 'env' },
  { name: "Spike Block Wide", path: "/assets-env/spike-block-wide.glb", category: 'env' },
  { name: "Spike Block", path: "/assets-env/spike-block.glb", category: 'env' },
  { name: "Spring", path: "/assets-env/spring.glb", category: 'env' },
  { name: "Star", path: "/assets-env/star.glb", category: 'env' },
  { name: "Stones", path: "/assets-env/stones.glb", category: 'env' },
  { name: "Trap Spikes Large", path: "/assets-env/trap-spikes-large.glb", category: 'env' },
  { name: "Trap Spikes", path: "/assets-env/trap-spikes.glb", category: 'env' },
  { name: "Tree Pine Small", path: "/assets-env/tree-pine-small.glb", category: 'env' },
  { name: "Tree Pine Snow Small", path: "/assets-env/tree-pine-snow-small.glb", category: 'env' },
  { name: "Tree Pine Snow", path: "/assets-env/tree-pine-snow.glb", category: 'env' },
  { name: "Tree Pine", path: "/assets-env/tree-pine.glb", category: 'env' },
  { name: "Tree Snow", path: "/assets-env/tree-snow.glb", category: 'env' },
  { name: "Tree", path: "/assets-env/tree.glb", category: 'env' },

  // TREE Assets
  { name: "Tree Type0 01", path: "/assets-tree/converted/Tree Type0 01.glb", category: 'tree' },
  { name: "Tree Type0 02", path: "/assets-tree/converted/Tree Type0 02.glb", category: 'tree' },
  { name: "Tree Type0 03", path: "/assets-tree/converted/Tree Type0 03.glb", category: 'tree' },
  { name: "Tree Type0 04", path: "/assets-tree/converted/Tree Type0 04.glb", category: 'tree' },
  { name: "Tree Type0 05", path: "/assets-tree/converted/Tree Type0 05.glb", category: 'tree' },
  { name: "Tree Type0 06", path: "/assets-tree/converted/Tree Type0 06.glb", category: 'tree' },
  { name: "Tree Type1 01", path: "/assets-tree/converted/Tree Type1 01.glb", category: 'tree' },
  { name: "Tree Type1 02", path: "/assets-tree/converted/Tree Type1 02.glb", category: 'tree' },
  { name: "Tree Type1 03", path: "/assets-tree/converted/Tree Type1 03.glb", category: 'tree' },
  { name: "Tree Type1 04", path: "/assets-tree/converted/Tree Type1 04.glb", category: 'tree' },
  { name: "Tree Type1 05", path: "/assets-tree/converted/Tree Type1 05.glb", category: 'tree' },
  { name: "Tree Type2 01", path: "/assets-tree/converted/Tree Type2 01.glb", category: 'tree' },
  { name: "Tree Type2 02", path: "/assets-tree/converted/Tree Type2 02.glb", category: 'tree' },
  { name: "Tree Type2 03", path: "/assets-tree/converted/Tree Type2 03.glb", category: 'tree' },
  { name: "Tree Type2 04", path: "/assets-tree/converted/Tree Type2 04.glb", category: 'tree' },
  { name: "Tree Type2 05", path: "/assets-tree/converted/Tree Type2 05.glb", category: 'tree' },
  { name: "Tree Type3 01", path: "/assets-tree/converted/Tree Type3 01.glb", category: 'tree' },
  { name: "Tree Type3 02", path: "/assets-tree/converted/Tree Type3 02.glb", category: 'tree' },
  { name: "Tree Type3 03", path: "/assets-tree/converted/Tree Type3 03.glb", category: 'tree' },
  { name: "Tree Type3 04", path: "/assets-tree/converted/Tree Type3 04.glb", category: 'tree' },
  { name: "Tree Type3 05", path: "/assets-tree/converted/Tree Type3 05.glb", category: 'tree' },
  { name: "Tree Type4 01", path: "/assets-tree/converted/Tree Type4 01.glb", category: 'tree' },
  { name: "Tree Type4 02", path: "/assets-tree/converted/Tree Type4 02.glb", category: 'tree' },
  { name: "Tree Type4 03", path: "/assets-tree/converted/Tree Type4 03.glb", category: 'tree' },
  { name: "Tree Type4 04", path: "/assets-tree/converted/Tree Type4 04.glb", category: 'tree' },
  { name: "Tree Type4 05", path: "/assets-tree/converted/Tree Type4 05.glb", category: 'tree' },
  { name: "Tree Type5 01", path: "/assets-tree/converted/Tree Type5 01.glb", category: 'tree' },
  { name: "Tree Type5 02", path: "/assets-tree/converted/Tree Type5 02.glb", category: 'tree' },
  { name: "Tree Type5 03", path: "/assets-tree/converted/Tree Type5 03.glb", category: 'tree' },
  { name: "Tree Type5 04", path: "/assets-tree/converted/Tree Type5 04.glb", category: 'tree' },
  { name: "Tree Type6 01", path: "/assets-tree/converted/Tree Type6 01.glb", category: 'tree' },
  { name: "Tree Type6 02", path: "/assets-tree/converted/Tree Type6 02.glb", category: 'tree' },
  { name: "Tree Type6 03", path: "/assets-tree/converted/Tree Type6 03.glb", category: 'tree' },
  { name: "Tree Type6 04", path: "/assets-tree/converted/Tree Type6 04.glb", category: 'tree' },
  { name: "Tree Type7 01", path: "/assets-tree/converted/Tree Type7 01.glb", category: 'tree' },
  { name: "Tree Type7 02", path: "/assets-tree/converted/Tree Type7 02.glb", category: 'tree' },
  { name: "Tree Type7 03", path: "/assets-tree/converted/Tree Type7 03.glb", category: 'tree' },
  { name: "Tree Type7 04", path: "/assets-tree/converted/Tree Type7 04.glb", category: 'tree' },

];

export const FULL_MATERIAL_LIBRARY: MaterialInfo[] = [
  {
    id: "texture_1",
    name: "Texture 1",
    diffuse: "/Textures/texture_1/textures/marble_cliff_03_diff_1k.jpg",
    displacement: "/Textures/texture_1/textures/marble_cliff_03_disp_1k.png",
  },
  {
    id: "texture_2",
    name: "Texture 2",
    diffuse: "/Textures/texture_2/textures/rocky_terrain_02_diff_1k.jpg",
    displacement: "/Textures/texture_2/textures/rocky_terrain_02_disp_1k.png",
  },
];